In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
veriler = pd.read_csv("veriler.csv")
print(veriler)
veriler.info()

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ulke      22 non-null     object
 1   boy       22 non-null     int64
 2   kilo      22 non-null     int64
 3   yas       22 non-null     int64
 4   cinsiyet  22 non-null     object
dtypes: int64(3), object(2)
memory usage: 1008.0+ bytes

In [3]:
from sklearn.preprocessing import OneHotEncoder
ulke = veriler[['ulke']].values
lb_cod = OneHotEncoder()

In [4]:
ulke = lb_cod.fit_transform(ulke).toarray()

In [5]:
veriler1 = veriler.drop(columns=['ulke'],axis=1)

In [6]:
ulke = pd.DataFrame(data=ulke,index=range(22),columns=['tr','us','fr'])
sonveriler = pd.concat([ulke,veriler1],axis=1)
sonveriler

     tr   us   fr  boy  kilo  yas cinsiyet
0   0.0  1.0  0.0  130    30   10        e
1   0.0  1.0  0.0  125    36   11        e
2   0.0  1.0  0.0  135    34   10        k
3   0.0  1.0  0.0  133    30    9        k
4   0.0  1.0  0.0  129    38   12        e
5   0.0  1.0  0.0  180    90   30        e
6   0.0  1.0  0.0  190    80   25        e
7   0.0  1.0  0.0  175    90   35        e
8   0.0  1.0  0.0  177    60   22        k
9   0.0  0.0  1.0  185   105   33        e
10  0.0  0.0  1.0  165    55   27        k
11  0.0  0.0  1.0  155    50   44        k
12  0.0  0.0  1.0  160    58   39        k
13  0.0  0.0  1.0  162    59   41        k
14  0.0  0.0  1.0  167    62   55        k
15  1.0  0.0  0.0  174    70   47        e
16  1.0  0.0  0.0  193    90   23        e
17  1.0  0.0  0.0  187    80   27        e
18  1.0  0.0  0.0  183    88   28        e
19  1.0  0.0  0.0  159    40   29        k
20  1.0  0.0  0.0  164    66   32        k
21  1.0  0.0  0.0  166    56   42        k

In [7]:
x = sonveriler.iloc[:,0:6].values
x

array([[  0.,   1.,   0., 130.,  30.,  10.],
       [  0.,   1.,   0., 125.,  36.,  11.],
       [  0.,   1.,   0., 135.,  34.,  10.],
       [  0.,   1.,   0., 133.,  30.,   9.],
       [  0.,   1.,   0., 129.,  38.,  12.],
       [  0.,   1.,   0., 180.,  90.,  30.],
       [  0.,   1.,   0., 190.,  80.,  25.],
       [  0.,   1.,   0., 175.,  90.,  35.],
       [  0.,   1.,   0., 177.,  60.,  22.],
       [  0.,   0.,   1., 185., 105.,  33.],
       [  0.,   0.,   1., 165.,  55.,  27.],
       [  0.,   0.,   1., 155.,  50.,  44.],
       [  0.,   0.,   1., 160.,  58.,  39.],
       [  0.,   0.,   1., 162.,  59.,  41.],
       [  0.,   0.,   1., 167.,  62.,  55.],
       [  1.,   0.,   0., 174.,  70.,  47.],
       [  1.,   0.,   0., 193.,  90.,  23.],
       [  1.,   0.,   0., 187.,  80.,  27.],
       [  1.,   0.,   0., 183.,  88.,  28.],
       [  1.,   0.,   0., 159.,  40.,  29.],
       [  1.,   0.,   0., 164.,  66.,  32.],
       [  1.,   0.,   0., 166.,  56.,  42.]])

In [8]:
y = sonveriler.iloc[:,-1].values
print(y)

['e' 'e' 'k' 'k' 'e' 'e' 'e' 'e' 'k' 'e' 'k' 'k' 'k' 'k' 'k' 'e' 'e' 'e'
 'e' 'k' 'k' 'k']

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1,leaf_size=30,weights='uniform',metric='minkowski')
knn.fit(X_train,y_train)
y_pred1 = knn.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred1)
print(cm)

[[1 0]
 [3 4]]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [18]:
error = [] 
for i in range(1, 22):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))
plt.figure(figsize=(12, 6))
plt.plot(range(1, 40), error, color='red')
plt.title('Error Rate K Value’)
plt.xlabel('K Value’)
plt.ylabel('Mean Error')

SyntaxError: EOL while scanning string literal (1034998199.py, line 9)